import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { AuthContextProvider } from "./contexts/auth_context";
import Navbar from "./ui/navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kummefryser",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <html lang="en">
    <html lang="en" className="no-scrollbar">
      <body className={`{inter.className}`}>
        <AuthContextProvider>
          <Navbar></Navbar>
          {children}
        </AuthContextProvider>
        <SpeedInsights />
      </body>
      {/* <body>{children}</body> */}
    </html>
  );
}
