import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { AuthContextProvider } from "./contexts/auth_context";
import Header from "./ui/navbar/header";
import Navbar from "./ui/navbar/navbar";
import { getAuthenticatedAppForUser } from "./lib/firebase/fierbase3";
import { FirebaseApp } from "firebase/app";
import { User } from "firebase/auth";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kummefryser",
  // description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { currentUser } = await getAuthenticatedAppForUser();
  return (
    // <html lang="en">
    <html lang="en" className="no-scrollbar">
      <body className={`{inter.className}`}>
        <AuthContextProvider>
          <Header initialUser={currentUser || null} />
          <Navbar></Navbar>
          {children}
        </AuthContextProvider>
        <SpeedInsights />
      </body>
      {/* <body>{children}</body> */}
    </html>
  );
}
