import { Category } from "../types/fooditem";

export const placeholderData = [
  {
    quantity: 1,
    name: "Kødsovs",
    category: Category.COOKED_DISH,
    freezeDate: new Date("2023-11-18"),
    expirationDate: new Date("2023-12-18"),
    durationDays: 30,
    volume: "ca. 1kg",
  },
  {
    quantity: 1,
    name: "Menneskehjerte",
    category: Category.COOKED_DISH,
    freezeDate: new Date("2023-10-18"),
    expirationDate: new Date("2024-1-18"),
    //   new Date("durationDays: 2024-1-18volume: "),
    durationDays: 90,
    volume: "ca. 1kg",
  },
  {
    quantity: 4,
    name: "Mango  i tern",
    category: Category.FRUIT,
    freezeDate: new Date("2023-12-10"),
    expirationDate: new Date("2024-4-10"),
    durationDays: 4 * 30,
    volume: "200g?",
  },
  {
    quantity: 1,
    name: "Jordbær",
    category: Category.FRUIT,
    freezeDate: new Date("2023-12-10"),
    expirationDate: new Date("2024-4-10"),
    durationDays: 4 * 30,
    volume: "500g?",
  },
  {
    quantity: 10,
    name: "Smør",
    category: Category.DAIRY,
    freezeDate: new Date("2023-12-10"),
    expirationDate: new Date("2024-10-10"),
    durationDays: 10 * 30,
    volume: "200g",
  },
  {
    quantity: 2,
    name: "Flæskesteg",
    category: Category.MEAT,
    freezeDate: new Date("2023-12-10"),
    expirationDate: new Date("2024-6-10"),
    durationDays: 6 * 30,
    volume: "~2 kg",
  },
];
